- name: Download familiar tools
  community.general.homebrew:
    name:
      - cmake
      - pass
      - make
      - gcc
      - sqlite
      - automake
      - llvm
      - unzip
      - wget
      - curl
      - ShellCheck
      - stow
      - git
    state: latest
